[application]
name = "pentest-connector"
default_platform = "android"
android_main_activity = "android/MainActivity.kt"

[bundle]
identifier = "com.strike48.pentest_connector"
publisher = "Strike48"

[web.app]
title = "Pentest Connector"
